---
title: Design Blocks
author: Not the mama
email: support@forestry.io
description: ''
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-menus
